# Generated by Django 5.0.4 on 2024-04-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อสินค้า')),
                ('qty', models.IntegerField(verbose_name='จำนวนสินค้า')),
                ('category', models.CharField(max_length=100, verbose_name='หมวดหมู่สินค้า')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ราคา')),
                ('update_at', models.DateField(auto_now=True, verbose_name='แก้ไขเมื่อ')),
            ],
        ),
    ]
